apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: webapp
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: webapp
          image: sunil0019/webapp:latest
          env:
          - name: USERNAME
            valueFrom:
              configMapKeyRef:
                name: myapp
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef: 
                name: mysecret
                key: password 
---
kind: Service
apiVersion: v1
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80