apiVersion: apps/v1
kind: Deployment
metadata:
  name: $app_name
spec:
  selector:
    matchLabels:
      app: $app_name
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: $app_name
    spec:
      containers:
      - name: $app_name
        image: sunil0019/$app_name:latest
      imagePullSecrets:
      - name: regcred
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: $app_name
spec:
  selector:
    app: $app_name
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80