apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{params.app_name}}"
spec:
  selector:
    matchLabels:
      app: "{{params.app_name}}"
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: "{{params.app_name}}"
    spec:
      containers:
      - name: "{{params.app_name}}"
        image: sunil0019/"{{params.app_name}}":latest
      imagePullSecrets:
      - name: regcred
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: "{{params.app_name}}"
spec:
  selector:
    app: "{{params.app_name}}"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80