#this workflow is to deploy in all the environments
name: web-app-release
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      argocd_server: 
        required: true
      argocd_username: 
        required: true
      argocd_password:
        required: true
      github_pat:
        required: true
      git_username:
        required: true

env:
  APP_NAME: webapp

jobs:
  deploy-dev:   
    name: Deploy-to-Dev
    runs-on: web-app
    # environment: 
    #   name: dev
    timeout-minutes: 60
    if: ${{ github.ref == 'refs/heads/main' && inputs.environment == 'dev'}}
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@v4
        with:
          repository: subramanya-au/k8s-manifests
          ref: main
          token: ${{ secrets.github_pat }}

      - name: checking files
        run: |
          ls -lart 
      
      - name: ArgoCD Deployment
        run: |
          #Argocd Login
          argocd login --insecure ${{ secrets.argocd_server }} --username ${{ secrets.argocd_username }} --password ${{ secrets.argocd_password }} --grpc-web

          #Argocd repo add
          argocd repo add https://github.com/subramanya-au/k8s-manifests.git --username ${{ secrets.git_username }} --password ${{ secrets.github_pat }} --insecure-skip-server-verification --grpc-web --upsert
      
          #Argocd app create
          kustomize build webapp/environments/sandbox | envsubst > deployment.yaml
          # argocd app create webapp -f webapp/environments/sandbox/application.yaml --upsert
          argocd app create ${{ env.APP_NAME }} -f deployment.yaml --upsert -n sandbox
          
          # #Set Image
          # argocd app set webapp --kustomize-image ${{ needs.continuous-integration.outputs.docker_image }}
  