#this workflow is to deploy in all the environments
name: web-app-release
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      app_name:
        required: true
        type: string
      github_url:
        required: true
        type: string
    secrets:
      argocd_server: 
        required: true
      argocd_username: 
        required: true
      argocd_password:
        required: true
      github_pat:
        required: true
      git_username:
        required: true

# env:
#   APP_NAME: webapp

jobs:
  deploy-dev:   
    name: Deploy-to-Dev
    runs-on: web-app
    # environment: 
    #   name: dev
    timeout-minutes: 60
    if: ${{ github.ref == 'refs/heads/main' && inputs.environment == 'dev'}}
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@v4
        with:
          repository: subramanya-au/k8s-manifests
          ref: main
          token: ${{ secrets.github_pat }}

      - name: checking files
        run: |
          ls -lart 
      
      - name: ArgoCD Deployment
        run: |
          #Argocd Login
          argocd login --insecure ${{ secrets.argocd_server }} --username ${{ secrets.argocd_username }} --password ${{ secrets.argocd_password }} --grpc-web

          #Argocd repo add
          argocd repo add https://github.com/subramanya-au/k8s-manifests.git --username ${{ secrets.git_username }} --password ${{ secrets.github_pat }} --insecure-skip-server-verification --grpc-web --upsert
      
          export app_name=${{ inputs.app_name }}
          kustomize build webapp/environments/sandbox | envsubst > main.yaml
          cat main.yaml 

          # argocd app create ${app_name} -f webapp/environments/sandbox/application.yaml --upsert | envsubst
          
          argocd app create ${{ inputs.app_name }} --repo https://github.com/subramanya-au/k8s-manifests.git \
                                      --path main.yaml --dest-namespace sandbox --dest-server https://kubernetes.default.svc --project default \
                                      --sync-option PruneLast=true --sync-option CreateNamespace=true \
                                      --sync-policy automated \
                                      --revision main \
                                      --upsert
                                  